version: "3.7"

services:
  app:
    build:
      context: ./netprog
    image: holprg2002
    volumes:
      - ./netprog:/app
    environment:
      - DEVICE_HOST=${DEVICE_HOST}
      - DEVICE_USER=${DEVICE_USER}
      - DEVICE_PASS=${DEVICE_PASS}
    ports:
      - "80:80"
    command: python manage.py runserver 0.0.0.0:80
